# Generated by Django 4.1.3 on 2022-12-05 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('state', models.CharField(choices=[('OP', 'Abierto'), ('PD', 'Pendiente'), ('IP', 'En proceso'), ('RS', 'Resuelto'), ('CL', 'Cerrado')], default='OP', max_length=2)),
                ('create_date', models.DateTimeField(verbose_name='Fecha de creación')),
            ],
        ),
    ]
