# Generated by Django 4.1.4 on 2022-12-14 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_ticket_create_date_alter_ticket_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'permissions': (('can_create', 'Crear un ticket'),)},
        ),
    ]
